
//
// SapphireColors.swift
//

// Do not edit directly, this file was auto-generated.


import SwiftUI

public struct SapphireColors {
    public static let rootPrimaryColorsBrandPrimary100 = Color(red: 0.337, green: 0.220, blue: 0.898, opacity: 1)
    public static let rootPrimaryColorsBrandPrimary50 = Color(red: 0.667, green: 0.608, blue: 0.949, opacity: 1)
    public static let rootPrimaryColorsBrandPrimary10 = Color(red: 0.902, green: 0.882, blue: 0.984, opacity: 1)
    public static let switchOsLayoutStrokeColor = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0)
    public static let switchOsColor = Color(red: 0.000, green: 0.000, blue: 0.000, opacity: 0.34901960784313724)
    public static let rootSecondaryColorsBrandSecondary300 = Color(red: 0.145, green: 0.220, blue: 0.322, opacity: 1)
    public static let rootSecondaryColorsBrandSecondary250 = Color(red: 0.329, green: 0.443, blue: 0.600, opacity: 1)
    public static let rootSecondaryColorsBrandSecondary200 = Color(red: 0.663, green: 0.722, blue: 0.800, opacity: 1)
    public static let rootSecondaryColorsBrandSecondary150 = Color(red: 0.867, green: 0.890, blue: 0.922, opacity: 1)
    public static let rootSecondaryColorsBrandSecondary100 = Color(red: 0.933, green: 0.945, blue: 0.961, opacity: 1)
    public static let rootGradientColorsBrandGradinetColor2 = Color(red: 0.431, green: 0.016, blue: 0.847, opacity: 1)
    public static let rootGradientColorsBrandGradinetColor4 = Color(red: 0.953, green: 0.961, blue: 0.973, opacity: 1)
    public static let rootNeutralColorsNeutral500 = Color(red: 0.000, green: 0.000, blue: 0.000, opacity: 1)
    public static let rootNeutralColorsNeutral400 = Color(red: 0.259, green: 0.259, blue: 0.259, opacity: 1)
    public static let rootNeutralColorsNeutral300 = Color(red: 0.553, green: 0.553, blue: 0.553, opacity: 1)
    public static let rootNeutralColorsNeutral200 = Color(red: 0.749, green: 0.749, blue: 0.749, opacity: 1)
    public static let rootNeutralColorsNeutral100 = Color(red: 0.906, green: 0.906, blue: 0.906, opacity: 1)
    public static let rootNeutralColorsNeutral0 = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 1)
    public static let rootStateColorsNegative100 = Color(red: 0.824, green: 0.086, blue: 0.086, opacity: 1)
    public static let rootStateColorsNegative50 = Color(red: 0.914, green: 0.541, blue: 0.541, opacity: 1)
    public static let rootStateColorsNegative10 = Color(red: 0.965, green: 0.816, blue: 0.816, opacity: 1)
    public static let rootStateColorsPositive100 = Color(red: 0.000, green: 0.706, blue: 0.408, opacity: 1)
    public static let rootStateColorsPositive50 = Color(red: 0.475, green: 0.843, blue: 0.686, opacity: 1)
    public static let rootStateColorsPositive10 = Color(red: 0.800, green: 0.941, blue: 0.882, opacity: 1)
    public static let rootStateColorsAttention100 = Color(red: 0.933, green: 0.525, blue: 0.051, opacity: 1)
    public static let rootStateColorsAttention50 = Color(red: 0.961, green: 0.718, blue: 0.431, opacity: 1)
    public static let rootStateColorsAttention10 = Color(red: 0.988, green: 0.906, blue: 0.812, opacity: 1)
    public static let rootStateColorsInformative100 = Color(red: 0.157, green: 0.349, blue: 0.616, opacity: 1)
    public static let rootStateColorsInformative50 = Color(red: 0.529, green: 0.651, blue: 0.808, opacity: 1)
    public static let rootStateColorsInformative10 = Color(red: 0.831, green: 0.871, blue: 0.922, opacity: 1)
    public static let rootOpacityPrimaryBrandOpacity1 = Color(red: 0.337, green: 0.220, blue: 0.898, opacity: 0)
    public static let rootOpacityPrimaryBrandOpacity2 = Color(red: 0.337, green: 0.220, blue: 0.898, opacity: 0.0784313725490196)
    public static let rootOpacityPrimaryBrandOpacity3 = Color(red: 0.337, green: 0.220, blue: 0.898, opacity: 0.10196078431372549)
    public static let rootOpacityPrimaryBrandOpacity4 = Color(red: 0.337, green: 0.220, blue: 0.898, opacity: 0.14901960784313725)
    public static let rootOpacityPrimaryBrandOpacity5 = Color(red: 0.337, green: 0.220, blue: 0.898, opacity: 0.2)
    public static let rootOpacityPrimaryBrandOpacity6 = Color(red: 0.337, green: 0.220, blue: 0.898, opacity: 0.25098039215686274)
    public static let rootOpacityPrimaryBrandOpacity7 = Color(red: 0.337, green: 0.220, blue: 0.898, opacity: 0.30196078431372547)
    public static let rootOpacityPrimaryBrandOpacity8 = Color(red: 0.337, green: 0.220, blue: 0.898, opacity: 0.34901960784313724)
    public static let rootOpacityPrimaryBrandOpacity9 = Color(red: 0.337, green: 0.220, blue: 0.898, opacity: 0.8)
    public static let rootOpacitySecondarySecondaryOpacity1 = Color(red: 0.145, green: 0.220, blue: 0.322, opacity: 0)
    public static let rootOpacitySecondarySecondaryOpacity2 = Color(red: 0.145, green: 0.220, blue: 0.322, opacity: 0.0784313725490196)
    public static let rootOpacitySecondarySecondaryOpacity3 = Color(red: 0.145, green: 0.220, blue: 0.322, opacity: 0.10196078431372549)
    public static let rootOpacitySecondarySecondaryOpacity4 = Color(red: 0.145, green: 0.220, blue: 0.322, opacity: 0.14901960784313725)
    public static let rootOpacitySecondarySecondaryOpacity5 = Color(red: 0.145, green: 0.220, blue: 0.322, opacity: 0.2)
    public static let rootOpacitySecondarySecondaryOpacity6 = Color(red: 0.145, green: 0.220, blue: 0.322, opacity: 0.25098039215686274)
    public static let rootOpacitySecondarySecondaryOpacity7 = Color(red: 0.145, green: 0.220, blue: 0.322, opacity: 0.30196078431372547)
    public static let rootOpacitySecondarySecondaryOpacity8 = Color(red: 0.145, green: 0.220, blue: 0.322, opacity: 0.34901960784313724)
    public static let rootOpacitySecondarySecondaryOpacity9 = Color(red: 0.145, green: 0.220, blue: 0.322, opacity: 0.8)
    public static let rootOpacityNeutralNeitralOpacity1 = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0)
    public static let rootOpacityNeutralNeitralOpacity2 = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0.0784313725490196)
    public static let rootOpacityNeutralNeitralOpacity3 = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0.10196078431372549)
    public static let rootOpacityNeutralNeitralOpacity4 = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0.14901960784313725)
    public static let rootOpacityNeutralNeitralOpacity5 = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0.2)
    public static let rootOpacityNeutralNeitralOpacity6 = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0.25098039215686274)
    public static let rootOpacityNeutralNeitralOpacity7 = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0.30196078431372547)
    public static let rootOpacityNeutralNeitralOpacity8 = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0.34901960784313724)
    public static let rootOpacityNeutralNeitralOpacity9 = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0.8)
    public static let rootOpacityNeutralNeitralOpacity10 = Color(red: 0.000, green: 0.000, blue: 0.000, opacity: 0.34901960784313724)
    public static let rootOpacityNeutralNeitralOpacity11 = Color(red: 0.733, green: 0.733, blue: 0.733, opacity: 0.30196078431372547)
    public static let switchOsStylesTransperancyColorFullGlass = rootNeutralColorsNeutral0
    public static let switchOsStylesTransperancyColorHalfGlass = rootNeutralColorsNeutral0
    public static let switchOsStylesTransperancyColorFrostedGlass = rootNeutralColorsNeutral0
    public static let switchOsStylesShadowsColorLargeSecondary = rootOpacitySecondarySecondaryOpacity8
    public static let switchOsComponentsOverlayFontColor = rootNeutralColorsNeutral500
    public static let switchOsComponentsOverlayBgContainerColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsInputNormalInputBackgroundColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsInputNormalInputIconColor = rootSecondaryColorsBrandSecondary250
    public static let switchOsComponentsInputNormalTextColor = rootSecondaryColorsBrandSecondary250
    public static let switchOsComponentsInputNormalInputStrokeColor = rootSecondaryColorsBrandSecondary150
    public static let switchOsComponentsInputSelectedInputBackgroundColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsInputSelectedTextColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsInputFilledInputBackgroundColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsInputFilledInputStrokeColor = rootSecondaryColorsBrandSecondary150
    public static let switchOsComponentsInputFilledInputIconColor = rootSecondaryColorsBrandSecondary200
    public static let switchOsComponentsInputFilledTextColor = rootSecondaryColorsBrandSecondary250
    public static let switchOsComponentsInputErrorInputBackgroundColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsInputErrorInputStrokeColor = rootStateColorsNegative100
    public static let switchOsComponentsInputErrorInputIconColor = rootStateColorsNegative100
    public static let switchOsComponentsInputErrorTextColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsInputSuccessInputBackgroundColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsInputSuccessInputStrokeColor = rootStateColorsPositive100
    public static let switchOsComponentsInputSuccessInputIconColor = rootStateColorsPositive100
    public static let switchOsComponentsInputSuccessTextColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsInputDisabledInputBackgroundColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsInputDisabledInputIconColor = rootSecondaryColorsBrandSecondary250
    public static let switchOsComponentsInputDisabledTextColor = rootSecondaryColorsBrandSecondary250
    public static let switchOsComponentsButtonPrimaryNormalTextColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsButtonPrimaryNormalBgGradientColor2 = rootGradientColorsBrandGradinetColor2
    public static let switchOsComponentsButtonPrimaryNormalIconColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsButtonPrimaryPressedTextColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsButtonPrimaryPressedIconColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsButtonPrimaryCancelTextColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsButtonPrimaryCancelIconColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsButtonPrimaryCancelBgColor = rootSecondaryColorsBrandSecondary200
    public static let switchOsComponentsButtonPrimaryDestructiveTextColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsButtonPrimaryDestructiveIconColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsButtonPrimaryDestructiveBgColor = rootStateColorsNegative100
    public static let switchOsComponentsButtonSecondaryNormalStrokeColor = rootSecondaryColorsBrandSecondary150
    public static let switchOsComponentsButtonSecondaryNormalIconColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsButtonSecondaryCancelIconColor = rootSecondaryColorsBrandSecondary200
    public static let switchOsComponentsButtonSecondaryCancelStrokeColor = rootSecondaryColorsBrandSecondary200
    public static let switchOsComponentsButtonSecondaryCancelTextColor = rootSecondaryColorsBrandSecondary200
    public static let switchOsComponentsButtonSecondaryDestructiveStrokeColor = rootStateColorsNegative100
    public static let switchOsComponentsButtonSecondaryDestructiveIconColor = rootStateColorsNegative100
    public static let switchOsComponentsButtonSecondaryDestructiveTextColor = rootStateColorsNegative100
    public static let switchOsComponentsSmallButtonPrimaryNormalTextColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsSmallButtonPrimaryNormalIconColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsSmallButtonPrimaryPressedTextColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsSmallButtonPrimaryPressedIconColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsSmallButtonPrimaryPressedBgColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsSmallButtonPrimaryCancelTextColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsSmallButtonPrimaryCancelIconColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsSmallButtonPrimaryCancelBgColor = rootSecondaryColorsBrandSecondary200
    public static let switchOsComponentsSmallButtonPrimaryDestructiveTextColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsSmallButtonPrimaryDestructiveIconColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsSmallButtonPrimaryDestructiveBgColor = rootStateColorsNegative100
    public static let switchOsComponentsSmallButtonSecondaryCancelTextColor = rootSecondaryColorsBrandSecondary200
    public static let switchOsComponentsSmallButtonSecondaryCancelIconColor = rootSecondaryColorsBrandSecondary200
    public static let switchOsComponentsSmallButtonSecondaryCancelStrokeColor = rootSecondaryColorsBrandSecondary200
    public static let switchOsComponentsSmallButtonSecondaryDestructiveTextColor = rootStateColorsNegative100
    public static let switchOsComponentsSmallButtonSecondaryDestructiveIconColor = rootStateColorsNegative100
    public static let switchOsComponentsSmallButtonSecondaryDestructiveStrokeColor = rootStateColorsNegative100
    public static let switchOsComponentsSmallButtonSecondaryNormalIconColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsSmallButtonSecondaryNormalStrokeColor = rootSecondaryColorsBrandSecondary150
    public static let switchOsComponentsOptionButtonNormalTextColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsOptionButtonNormalIconColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsFloatingButtonPrimaryColoredIconColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsFloatingButtonPrimaryNormalBgColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsFloatingButtonPrimaryCancelIconColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsFloatingButtonPrimaryCancelBgColor = rootSecondaryColorsBrandSecondary150
    public static let switchOsComponentsFloatingButtonPrimaryDestructiveIconColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsFloatingButtonPrimaryDestructiveBgColor = rootStateColorsNegative100
    public static let switchOsComponentsFloatingButtonSecondaryNormalStrokeColor = rootSecondaryColorsBrandSecondary150
    public static let switchOsComponentsFloatingButtonSecondaryCancelIconColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsFloatingButtonSecondaryCancelStrokeColor = rootSecondaryColorsBrandSecondary150
    public static let switchOsComponentsFloatingButtonSecondaryDestructiveIconColor = rootStateColorsNegative100
    public static let switchOsComponentsFloatingButtonSecondaryDestructiveStrokeColor = rootStateColorsNegative100
    public static let switchOsComponentsDropdownNormalBackgroundColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsDropdownNormalStrokeColor = rootSecondaryColorsBrandSecondary150
    public static let switchOsComponentsDropdownNormalIconColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsDropdownNormalTextColor = rootSecondaryColorsBrandSecondary250
    public static let switchOsComponentsDropdownSelectedBackgroundColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsDropdownSelectedIconColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsDropdownSelectedTextColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsDropdownFilledBackgroundColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsDropdownFilledStrokeColor = rootSecondaryColorsBrandSecondary150
    public static let switchOsComponentsDropdownFilledIconColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsDropdownFilledTextColor = rootSecondaryColorsBrandSecondary250
    public static let switchOsComponentsDropdownErrorBackgroundColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsDropdownErrorStrokeColor = rootStateColorsNegative100
    public static let switchOsComponentsDropdownErrorIconColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsDropdownErrorTextColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsDropdownSuccessBackgroundColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsDropdownSuccessStrokeColor = rootStateColorsPositive100
    public static let switchOsComponentsDropdownSuccessIconColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsDropdownSuccessTextColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsDropdownDisabledBackgroundColor = rootSecondaryColorsBrandSecondary150
    public static let switchOsComponentsDropdownDisabledIconColor = rootSecondaryColorsBrandSecondary200
    public static let switchOsComponentsDropdownDisabledTextColor = rootSecondaryColorsBrandSecondary250
    public static let switchOsComponentsTextareaNormalBackgroundColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsTextareaNormalStrokeColor = rootSecondaryColorsBrandSecondary150
    public static let switchOsComponentsTextareaNormalTextColor = rootSecondaryColorsBrandSecondary250
    public static let switchOsComponentsTextareaSelectedBackgroundColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsTextareaSelectedTextColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsTextareaFilledBackgroundColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsTextareaFilledStrokeColor = rootSecondaryColorsBrandSecondary150
    public static let switchOsComponentsTextareaFilledTextColor = rootSecondaryColorsBrandSecondary250
    public static let switchOsComponentsTextareaErrorBackgroundColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsTextareaErrorStrokeColor = rootStateColorsNegative100
    public static let switchOsComponentsTextareaErrorTextColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsTextareaSuccessBackgroundColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsTextareaSuccessStrokeColor = rootStateColorsPositive100
    public static let switchOsComponentsTextareaSuccessTextColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsTextareaDisabledBackgroundColor = rootSecondaryColorsBrandSecondary150
    public static let switchOsComponentsTextareaDisabledTextColor = rootSecondaryColorsBrandSecondary250
    public static let switchOsComponentsCheckmarkNormalStrokeColor = rootSecondaryColorsBrandSecondary150
    public static let switchOsComponentsCheckmarkNormalBgColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsCheckmarkSelectedStrokeColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsCheckmarkSelectedIconColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsCheckmarkFontColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsRadioButtonNormalStrokeColor = rootSecondaryColorsBrandSecondary150
    public static let switchOsComponentsRadioButtonNormalBgColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsRadioButtonFontColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsRadioButtonSelectedBgColor = rootSecondaryColorsBrandSecondary150
    public static let switchOsComponentsRadioButtonSelectedStrokeColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsNavElementDefaultIconColor = rootNeutralColorsNeutral500
    public static let switchOsComponentsNavElementDefaultFontColor = rootNeutralColorsNeutral500
    public static let switchOsComponentsPagesNormal = rootNeutralColorsNeutral100
    public static let switchOsComponentsListMenuNormalBgColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsListMenuNormalFontColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsListMenuNormalIconColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsListMenuPressedBgColor = rootSecondaryColorsBrandSecondary150
    public static let switchOsComponentsListMenuPressedIconColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsTabButtonSelectedBgColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsTabButtonNormalBgColor = rootSecondaryColorsBrandSecondary100
    public static let switchOsComponentsTabButtonNormalIconColor = rootSecondaryColorsBrandSecondary250
    public static let switchOsComponentsTabButtonNormalFontColor = rootSecondaryColorsBrandSecondary250
    public static let switchOsComponentsSearchActiveBgColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsSearchActiveFontColor = rootNeutralColorsNeutral500
    public static let switchOsComponentsSearchActiveCloseIconColor = rootNeutralColorsNeutral200
    public static let switchOsComponentsSearchNormalBgColor = rootOpacityNeutralNeitralOpacity11
    public static let switchOsComponentsSearchNormalIconColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsSearchNormalFontColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsOptionIconBgColor = rootOpacityNeutralNeitralOpacity11
    public static let switchOsComponentsOptionIconIconColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsDescriptionBoxBgColor = rootSecondaryColorsBrandSecondary100
    public static let switchOsComponentsDescriptionBoxFontColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsCardStrokeColor = rootSecondaryColorsBrandSecondary100
    public static let switchOsComponentsCardMainTextFontColor = rootNeutralColorsNeutral500
    public static let switchOsComponentsCardSupportFontColor = rootSecondaryColorsBrandSecondary250
    public static let switchOsComponentsCardIconIconSupportColor = rootNeutralColorsNeutral300
    public static let switchOsComponentsCardBgColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsStepsFontColor = rootNeutralColorsNeutral500
    public static let switchOsComponentsStepsInactiveBgColor = rootNeutralColorsNeutral100
    public static let switchOsComponentsStepsSuccessBgColor = rootStateColorsPositive100
    public static let switchOsComponentsStepsIconColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsStatusTagNegativeStrokeColor = rootStateColorsNegative100
    public static let switchOsComponentsStatusTagNegativeBgColor = rootStateColorsNegative10
    public static let switchOsComponentsStatusTagNegativeIconColor = rootStateColorsNegative100
    public static let switchOsComponentsStatusTagFontColor = rootNeutralColorsNeutral500
    public static let switchOsComponentsStatusTagPositiveStrokeColor = rootStateColorsPositive100
    public static let switchOsComponentsStatusTagPositiveIconColor = rootStateColorsPositive100
    public static let switchOsComponentsStatusTagPositiveBgColor = rootStateColorsPositive10
    public static let switchOsComponentsStatusTagAttentionStrokeColor = rootStateColorsAttention100
    public static let switchOsComponentsStatusTagAttentionIconColor = rootStateColorsAttention100
    public static let switchOsComponentsStatusTagAttentionBgColor = rootStateColorsAttention10
    public static let switchOsComponentsStatusTagInformativeStrokeColor = rootStateColorsInformative100
    public static let switchOsComponentsStatusTagInformativeIconColor = rootStateColorsInformative100
    public static let switchOsComponentsStatusTagInformativeBgColor = rootStateColorsInformative10
    public static let switchOsComponentsStatusTagDefaultStrokeColor = rootNeutralColorsNeutral100
    public static let switchOsComponentsStatusTagDefaultIconColor = rootNeutralColorsNeutral300
    public static let switchOsComponentsStatusTagDefaultBgColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsToastFontColor = rootNeutralColorsNeutral500
    public static let switchOsComponentsToastNegativeStrokeColor = rootStateColorsNegative100
    public static let switchOsComponentsToastNegativeIconBgColor = rootStateColorsNegative100
    public static let switchOsComponentsToastNegativeGradientBgColor2 = rootStateColorsNegative100
    public static let switchOsComponentsToastNegativeCloseIconColor = rootStateColorsNegative100
    public static let switchOsComponentsToastPositiveStrokeColor = rootStateColorsPositive100
    public static let switchOsComponentsToastPositiveCloseIconColor = rootStateColorsPositive100
    public static let switchOsComponentsToastPositiveGradientBgColor2 = rootStateColorsPositive100
    public static let switchOsComponentsToastPositiveIconBgColor = rootStateColorsPositive100
    public static let switchOsComponentsToastInformativeStrokeColor = rootStateColorsInformative100
    public static let switchOsComponentsToastInformativeCloseIconColor = rootStateColorsInformative100
    public static let switchOsComponentsToastInformativeGradientBgColor2 = rootStateColorsInformative50
    public static let switchOsComponentsToastInformativeIconBgColor = rootStateColorsInformative100
    public static let switchOsComponentsToastIconColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsToastGradientBgColor1 = rootNeutralColorsNeutral0
    public static let switchOsComponentsSpaceBrandingBgColor = rootNeutralColorsNeutral0
    public static let switchOsComponentsSpaceBrandingIconColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsSpaceBrandingFontColor = rootSecondaryColorsBrandSecondary300
    public static let switchOsComponentsSpaceBrandingStrokeColor = rootSecondaryColorsBrandSecondary100
    public static let rootGradientColorsBrandGradinetColor1 = rootPrimaryColorsBrandPrimary100
    public static let rootGradientColorsBrandGradinetColor3 = rootNeutralColorsNeutral0
    public static let aliasPrimaryColorsAccentBrandDefault = rootPrimaryColorsBrandPrimary100
    public static let aliasPrimaryColorsAccentBrandLight = rootPrimaryColorsBrandPrimary50
    public static let aliasPrimaryColorsAccentBrandLighter = rootPrimaryColorsBrandPrimary10
    public static let aliasOpacityNeutralNeutralWOpaicity0 = rootOpacityNeutralNeitralOpacity1
    public static let aliasOpacityNeutralNeutralWOpaicity8 = rootOpacityNeutralNeitralOpacity2
    public static let aliasOpacityNeutralNeutralWOpaicity10 = rootOpacityNeutralNeitralOpacity3
    public static let aliasOpacityNeutralNeutralWOpaicity15 = rootOpacityNeutralNeitralOpacity4
    public static let aliasOpacityNeutralNeutralWOpaicity20 = rootOpacityNeutralNeitralOpacity5
    public static let aliasOpacityNeutralNeutralWOpaicity25 = rootOpacityNeutralNeitralOpacity6
    public static let aliasOpacityNeutralNeutralWOpaicity30 = rootOpacityNeutralNeitralOpacity7
    public static let aliasOpacityNeutralNeutralWOpaicity35 = rootOpacityNeutralNeitralOpacity8
    public static let aliasOpacityNeutralNeutralWOpaicity80 = rootOpacityNeutralNeitralOpacity9
    public static let aliasOpacityNeutralNeutralBOpaicity35 = rootOpacityNeutralNeitralOpacity10
    public static let aliasOpacityNeutralNeutralGOpaicity30 = rootOpacityNeutralNeitralOpacity11
    public static let aliasOpacitySecondaryScondaryOpacity0 = rootOpacitySecondarySecondaryOpacity1
    public static let aliasOpacitySecondaryScondaryOpacity8 = rootOpacitySecondarySecondaryOpacity2
    public static let aliasOpacitySecondaryScondaryOpacity10 = rootOpacitySecondarySecondaryOpacity3
    public static let aliasOpacitySecondaryScondaryOpacity15 = rootOpacitySecondarySecondaryOpacity4
    public static let aliasOpacitySecondaryScondaryOpacity20 = rootOpacitySecondarySecondaryOpacity5
    public static let aliasOpacitySecondaryScondaryOpacity25 = rootOpacitySecondarySecondaryOpacity6
    public static let aliasOpacitySecondaryScondaryOpacity30 = rootOpacitySecondarySecondaryOpacity7
    public static let aliasOpacitySecondaryScondaryOpacity35 = rootOpacitySecondarySecondaryOpacity8
    public static let aliasOpacitySecondaryScondaryOpacity80 = rootOpacitySecondarySecondaryOpacity9
    public static let aliasOpacityPrimaryBrandOpacity0 = rootOpacityPrimaryBrandOpacity1
    public static let aliasOpacityPrimaryBrandOpacity8 = rootOpacityPrimaryBrandOpacity2
    public static let aliasOpacityPrimaryBrandOpacity10 = rootOpacityPrimaryBrandOpacity3
    public static let aliasOpacityPrimaryBrandOpacity15 = rootOpacityPrimaryBrandOpacity4
    public static let aliasOpacityPrimaryBrandOpacity20 = rootOpacityPrimaryBrandOpacity5
    public static let aliasOpacityPrimaryBrandOpacity25 = rootOpacityPrimaryBrandOpacity6
    public static let aliasOpacityPrimaryBrandOpacity30 = rootOpacityPrimaryBrandOpacity7
    public static let aliasOpacityPrimaryBrandOpacity35 = rootOpacityPrimaryBrandOpacity8
    public static let aliasOpacityPrimaryBrandOpacity80 = rootOpacityPrimaryBrandOpacity9
    public static let switchOsGlobalFrameWidth = aliasScreenSizeSizeFullAndroid
    public static let switchOsGlobalContainerWidth = aliasContainerSizeSizeContainerAndroid
    public static let switchOsLayoutPaddingSmallLeft = aliasSpacingPaddingPadding12
    public static let switchOsLayoutPaddingSmallRight = aliasSpacingPaddingPadding12
    public static let switchOsLayoutPaddingSmallTop = aliasSpacingPaddingPadding12
    public static let switchOsLayoutPaddingSmallBottom = aliasSpacingPaddingPadding12
    public static let switchOsLayoutPaddingMediumLeft = aliasSpacingPaddingPadding18
    public static let switchOsLayoutPaddingMediumRight = aliasSpacingPaddingPadding18
    public static let switchOsLayoutPaddingMediumTop = aliasSpacingPaddingPadding18
    public static let switchOsLayoutPaddingMediumBottom = aliasSpacingPaddingPadding18
    public static let switchOsLayoutPaddingLargeLeft = aliasSpacingPaddingPadding22
    public static let switchOsLayoutPaddingLargeRight = aliasSpacingPaddingPadding22
    public static let switchOsLayoutPaddingLargeTop = aliasSpacingPaddingPadding22
    public static let switchOsLayoutPaddingLargeBottom = aliasSpacingPaddingPadding22
    public static let switchOsLayoutSpacingLarge = aliasSpacingGapGap24
    public static let switchOsLayoutSpacingMedium = aliasSpacingGapGap16
    public static let switchOsLayoutSpacingSmall = aliasSpacingGapGap8
    public static let switchOsLayoutSpacingExtraLarge = aliasSpacingGapGap30
    public static let switchOsLayoutSpacingExtraSmall = aliasSpacingGapGap2
    public static let switchOsStylesTransperancyBlurFrostedGlass = aliasBlurBlursize0
    public static let switchOsStylesTransperancyBlurHalfGlass = aliasBlurBlursize0
    public static let switchOsStylesTransperancyBlurFullGlass = aliasBlurBlursize0
    public static let switchOsStylesShadowsSizeSmallX = aliasShadowsOffsetShadowOffsetx0
    public static let switchOsStylesShadowsSizeSmallY = aliasShadowsOffsetShadowOffsety0
    public static let switchOsStylesShadowsSizeSmallBlur = aliasBlurBlursize0
    public static let switchOsStylesShadowsSizeMediumX = aliasShadowsOffsetShadowOffsetx0
    public static let switchOsStylesShadowsSizeMediumY = aliasShadowsOffsetShadowOffsety0
    public static let switchOsStylesShadowsSizeMediumBlur = aliasBlurBlursize0
    public static let switchOsStylesShadowsSizeLargeX = aliasShadowsOffsetShadowOffsetx0
    public static let switchOsStylesShadowsSizeLargeY = aliasShadowsOffsetShadowOffsety2
    public static let switchOsStylesShadowsSizeLargeBlur = aliasBlurBlursize4
    public static let switchOsStylesShadowsColorSmallSecondary = aliasOpacitySecondaryScondaryOpacity0
    public static let switchOsStylesShadowsColorSmallColor = aliasOpacityPrimaryBrandOpacity0
    public static let switchOsStylesShadowsColorMediumSecondary = aliasOpacitySecondaryScondaryOpacity0
    public static let switchOsStylesShadowsColorMediumColor = aliasOpacityPrimaryBrandOpacity0
    public static let switchOsStylesShadowsColorLargeColor = aliasOpacityPrimaryBrandOpacity15
    public static let switchOsComponentsNavigationSizeW = aliasScreenSizeSizeFullAndroid
    public static let switchOsComponentsNavigationPaddingLeft = aliasSpacingPaddingPadding30
    public static let switchOsComponentsNavigationPaddingRight = aliasSpacingPaddingPadding30
    public static let switchOsComponentsNavigationPaddingTop = aliasSpacingPaddingPadding16
    public static let switchOsComponentsNavigationBorderRadius = aliasBorderRadiusBorderRadius0
    public static let switchOsComponentsOverlayBgColor = aliasOpacityNeutralNeutralBOpaicity35
    public static let switchOsComponentsOverlayTitleFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsComponentsOverlayTitleFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsComponentsOverlayTitleFontSize = aliasFontSizeFontSize24
    public static let switchOsComponentsOverlayContainerSizeW = aliasScreenSizeSizeFullAndroid
    public static let switchOsComponentsOverlayContainerRadius = aliasBorderRadiusBorderRadius18
    public static let switchOsComponentsOverlayDescriptionFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsComponentsOverlayDescriptionFontSize = aliasFontSizeFontSize15
    public static let switchOsComponentsOverlayDescriptionFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsComponentsOverlayGap = aliasSpacingGapGap24
    public static let switchOsComponentsOverlayPaddingH = aliasSpacingPaddingPadding20
    public static let switchOsComponentsOverlayPaddingTop = aliasSpacingPaddingPadding20
    public static let switchOsComponentsOverlayPaddingBottom = aliasSpacingPaddingPadding20
    public static let switchOsComponentsInputInputPaddingLeft = aliasSpacingPaddingPadding18
    public static let switchOsComponentsInputGap = aliasSpacingGapGap8
    public static let switchOsComponentsInputInputPaddingTop = aliasSpacingPaddingPadding18
    public static let switchOsComponentsInputInputPaddingRight = aliasSpacingPaddingPadding18
    public static let switchOsComponentsInputInputPaddingBottom = aliasSpacingPaddingPadding18
    public static let switchOsComponentsInputBorderRadius = aliasBorderRadiusBorderRadius8
    public static let switchOsComponentsInputSelectedInputStrokeColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsInputSelectedInputIconColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsButtonPrimaryNormalBgGradientColor1 = rootGradientColorsBrandGradinetColor1
    public static let switchOsComponentsButtonPrimaryPressedBgColor = aliasPrimaryColorsAccentBrandLight
    public static let switchOsComponentsButtonRadius = aliasBorderRadiusBorderRadiusFull
    public static let switchOsComponentsButtonPaddingX = aliasSpacingPaddingPadding20
    public static let switchOsComponentsButtonGap = aliasSpacingGapGap10
    public static let switchOsComponentsButtonFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsComponentsButtonFontSize = aliasFontSizeFontSize20
    public static let switchOsComponentsButtonFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsComponentsButtonSecondaryNormalTextColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsButtonSecondaryPressedStrokeColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsButtonSecondaryPressedIconColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsButtonSecondaryPressedTextColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsButtonPaddingY = aliasSpacingPaddingPadding16
    public static let switchOsComponentsSmallButtonRadius = aliasBorderRadiusBorderRadiusFull
    public static let switchOsComponentsSmallButtonPaddingH = aliasSpacingPaddingPadding12
    public static let switchOsComponentsSmallButtonGap = aliasSpacingGapGap4
    public static let switchOsComponentsSmallButtonFontSize = aliasFontSizeFontSize15
    public static let switchOsComponentsSmallButtonFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsComponentsSmallButtonFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsComponentsSmallButtonPrimaryNormalBgColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsSmallButtonSecondaryPressedTextColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsSmallButtonSecondaryPressedIconColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsSmallButtonSecondaryPressedStrokeColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsSmallButtonSecondaryNormalTextColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsSmallButtonPaddingV = aliasSpacingPaddingPadding6
    public static let switchOsComponentsOptionButtonGap = aliasSpacingGapGap8
    public static let switchOsComponentsOptionButtonFontSize = aliasFontSizeFontSize15
    public static let switchOsComponentsOptionButtonFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsComponentsOptionButtonFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsComponentsOptionButtonPressedTextColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsOptionButtonPressedIconColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsFloatingButtonPrimaryColoredBgColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsFloatingButtonPrimaryNormalIconColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsFloatingButtonSecondaryNormalIconColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsFloatingButtonSecondarySecondaryIconColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsFloatingButtonSecondarySecondaryStrokeColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsDropdownPaddingLeft = aliasSpacingPaddingPadding18
    public static let switchOsComponentsDropdownPaddingTop = aliasSpacingPaddingPadding18
    public static let switchOsComponentsDropdownPaddingRight = aliasSpacingPaddingPadding18
    public static let switchOsComponentsDropdownPaddingBottom = aliasSpacingPaddingPadding18
    public static let switchOsComponentsDropdownGapH = aliasSpacingGapGap8
    public static let switchOsComponentsDropdownBorderRadius = aliasBorderRadiusBorderRadius8
    public static let switchOsComponentsDropdownSelectedStrokeColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsTextareaPaddingLeft = aliasSpacingPaddingPadding18
    public static let switchOsComponentsTextareaPaddingTop = aliasSpacingPaddingPadding18
    public static let switchOsComponentsTextareaPaddingRight = aliasSpacingPaddingPadding18
    public static let switchOsComponentsTextareaPaddingBottom = aliasSpacingPaddingPadding18
    public static let switchOsComponentsTextareaGapH = aliasSpacingGapGap8
    public static let switchOsComponentsTextareaBorderRadius = aliasBorderRadiusBorderRadius8
    public static let switchOsComponentsTextareaSelectedStrokeColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsCheckmarkBorderRadius = aliasBorderRadiusBorderRadius4
    public static let switchOsComponentsCheckmarkSelectedBgColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsCheckmarkGap = aliasSpacingGapGap10
    public static let switchOsComponentsCheckmarkFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsComponentsCheckmarkFontSize = aliasFontSizeFontSize14
    public static let switchOsComponentsCheckmarkFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsComponentsRadioButtonBorderRadius = aliasBorderRadiusBorderRadiusFull
    public static let switchOsComponentsRadioButtonGap = aliasSpacingGapGap10
    public static let switchOsComponentsRadioButtonFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsComponentsRadioButtonFontSize = aliasFontSizeFontSize14
    public static let switchOsComponentsRadioButtonFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsComponentsNavElementDefaultFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsComponentsNavElementDefaultFontSize = aliasFontSizeFontSize14
    public static let switchOsComponentsNavElementDefaultFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsComponentsNavElementGap = aliasSpacingGapGap2
    public static let switchOsComponentsNavElementActiveIconColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsNavElementActiveFontColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsNavElementActiveFontSize = aliasFontSizeFontSize14
    public static let switchOsComponentsNavElementActiveFontWeight = aliasFontWeightFontWeightSemibold
    public static let switchOsComponentsNavElementActiveFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsComponentsPagesSelected = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsListMenuBorderRadius = aliasBorderRadiusBorderRadius18
    public static let switchOsComponentsListMenuNormalStrokeColor = aliasOpacityNeutralNeutralWOpaicity0
    public static let switchOsComponentsListMenuNormalFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsComponentsListMenuNormalFontSize = aliasFontSizeFontSize16
    public static let switchOsComponentsListMenuNormalFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsComponentsListMenuSizeW = aliasContainerSizeSizeContainerAndroid
    public static let switchOsComponentsListMenuGap = aliasSpacingGapGap10
    public static let switchOsComponentsListMenuPressedFontColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsListMenuPressedFontWeight = aliasFontWeightFontWeightMedium
    public static let switchOsComponentsListMenuPressedFontSize = aliasFontSizeFontSize16
    public static let switchOsComponentsListMenuPressedFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsComponentsListMenuPressedStrokeColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsListMenuPaddingLeft = aliasSpacingPaddingPadding16
    public static let switchOsComponentsListMenuPaddingRight = aliasSpacingPaddingPadding16
    public static let switchOsComponentsTabButtonSelectedFontSize = aliasFontSizeFontSize14
    public static let switchOsComponentsTabButtonSelectedFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsComponentsTabButtonSelectedIconColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsTabButtonSelectedFontColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsTabButtonSelectedFontWeight = aliasFontWeightFontWeightSemibold
    public static let switchOsComponentsTabButtonNormalFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsComponentsTabButtonNormalFontSize = aliasFontSizeFontSize14
    public static let switchOsComponentsTabButtonNormalFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsComponentsTabButtonBorderRadius = aliasBorderRadiusBorderRadiusFull
    public static let switchOsComponentsTabButtonGap = aliasSpacingGapGap8
    public static let switchOsComponentsTabButtonPaddingV = aliasSpacingPaddingPadding20
    public static let switchOsComponentsTabButtonPaddingH = aliasSpacingPaddingPadding20
    public static let switchOsComponentsSearchActiveIconColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsSearchBorderRadius = aliasBorderRadiusBorderRadiusFull
    public static let switchOsComponentsSearchGap = aliasSpacingGapGap8
    public static let switchOsComponentsSearchPaddingLeft = aliasSpacingPaddingPadding12
    public static let switchOsComponentsSearchPaddingRight = aliasSpacingPaddingPadding12
    public static let switchOsComponentsSearchPaddingTop = aliasSpacingPaddingPadding12
    public static let switchOsComponentsSearchPaddingBottom = aliasSpacingPaddingPadding12
    public static let switchOsComponentsSearchFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsComponentsSearchFontSize = aliasFontSizeFontSize12
    public static let switchOsComponentsSearchFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsComponentsOptionIconBorderRadius = aliasBorderRadiusBorderRadiusFull
    public static let switchOsComponentsDescriptionBoxBorderRadius = aliasBorderRadiusBorderRadius18
    public static let switchOsComponentsDescriptionBoxSizeW = aliasContainerSizeSizeContainerAndroid
    public static let switchOsComponentsDescriptionBoxGap = aliasSpacingGapGap8
    public static let switchOsComponentsDescriptionBoxPaddingH = aliasSpacingPaddingPadding16
    public static let switchOsComponentsDescriptionBoxPaddingV = aliasSpacingPaddingPadding16
    public static let switchOsComponentsCardBorderRadius = aliasBorderRadiusBorderRadius18
    public static let switchOsComponentsCardSizeW = aliasContainerSizeSizeContainerAndroid
    public static let switchOsComponentsCardMainTextFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsComponentsCardMainTextFontSize = aliasFontSizeFontSize16
    public static let switchOsComponentsCardMainTextFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsComponentsCardGap = aliasSpacingGapGap10
    public static let switchOsComponentsCardPaddingLeft = aliasSpacingPaddingPadding12
    public static let switchOsComponentsCardPaddingBottom = aliasSpacingPaddingPadding12
    public static let switchOsComponentsCardPaddingRight = aliasSpacingPaddingPadding12
    public static let switchOsComponentsCardPaddingTop = aliasSpacingPaddingPadding12
    public static let switchOsComponentsCardSupportFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsComponentsCardSupportFontSize = aliasFontSizeFontSize12
    public static let switchOsComponentsCardSupportFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsComponentsCardIconIconColorNormal = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsCardIconIconColorSelected = aliasPrimaryColorsAccentBrandLighter
    public static let switchOsComponentsCardIconBgColorNormal = aliasPrimaryColorsAccentBrandLighter
    public static let switchOsComponentsCardIconBgColorSelected = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsCardGap2 = aliasSpacingGapGap8
    public static let switchOsComponentsCardStrokeActiveColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsStepsBorderRadius = aliasBorderRadiusBorderRadiusFull
    public static let switchOsComponentsStepsActiveBgColor = aliasPrimaryColorsAccentBrandDefault
    public static let switchOsComponentsStepsInfoTextFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsComponentsStepsInfoTextFontSize = aliasFontSizeFontSize14
    public static let switchOsComponentsStepsInfoTextFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsComponentsStepsStepTextFontSize = aliasFontSizeFontSize14
    public static let switchOsComponentsStepsStepTextFontWeight = aliasFontWeightFontWeightSemibold
    public static let switchOsComponentsStepsStepTextFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsComponentsStatusTagGap = aliasSpacingGapGap8
    public static let switchOsComponentsStatusTagFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsComponentsStatusTagFontSize = aliasFontSizeFontSize12
    public static let switchOsComponentsStatusTagFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsComponentsStatusTagPaddingV = aliasSpacingPaddingPadding6
    public static let switchOsComponentsStatusTagPaddingH = aliasSpacingPaddingPadding10
    public static let switchOsComponentsStatusTagBorderRadius = aliasBorderRadiusBorderRadiusFull
    public static let switchOsComponentsToastGap = aliasSpacingGapGap10
    public static let switchOsComponentsToastPaddingH = aliasSpacingPaddingPadding16
    public static let switchOsComponentsToastPaddingV = aliasSpacingPaddingPadding12
    public static let switchOsComponentsToastFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsComponentsToastFontSize = aliasFontSizeFontSize14
    public static let switchOsComponentsToastFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsComponentsToastBorderRadius = aliasBorderRadiusBorderRadius18
    public static let switchOsComponentsToastSizeW = aliasContainerSizeSizeContainerAndroid
    public static let switchOsComponentsSpaceBrandingFontSize = aliasFontSizeFontSize18
    public static let switchOsComponentsSpaceBrandingFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsComponentsSpaceBrandingFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsComponentsSpaceBrandingSizeW = aliasContainerSizeSizeContainerAndroid
    public static let switchOsComponentsSpaceBrandingCornerRadiusTopRight = aliasBorderRadiusBorderRadius18
    public static let switchOsComponentsSpaceBrandingCornerRadiusTopLeft = aliasBorderRadiusBorderRadius18
    public static let switchOsComponentsSpaceBrandingCornerRadiusBottomLeft = aliasBorderRadiusBorderRadius18
    public static let switchOsComponentsSpaceBrandingCornerRadiusBottomRight = aliasBorderRadiusBorderRadius18
    public static let switchOsComponentsSpaceBrandingGap = aliasSpacingGapGap12
    public static let switchOsFontsLargeTitleNormalFontSize = aliasFontSizeFontSize30
    public static let switchOsFontsLargeTitleNormalFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsFontsLargeTitleNormalFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsFontsMediumTitleNormalFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsFontsMediumTitleNormalFontSize = aliasFontSizeFontSize24
    public static let switchOsFontsMediumTitleNormalFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsFontsMediumTitleStrongFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsFontsMediumTitleStrongFontSize = aliasFontSizeFontSize24
    public static let switchOsFontsMediumTitleStrongFontWeight = aliasFontWeightFontWeightBold
    public static let switchOsFontsSmallTitleStrongFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsFontsSmallTitleStrongFontSize = aliasFontSizeFontSize20
    public static let switchOsFontsSmallTitleStrongFontWeight = aliasFontWeightFontWeightBold
    public static let switchOsFontsSmallTitleNormalFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsFontsSmallTitleNormalFontSize = aliasFontSizeFontSize20
    public static let switchOsFontsSmallTitleNormalFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsFontsSubpageTitleNormalFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsFontsSubpageTitleNormalFontSize = aliasFontSizeFontSize18
    public static let switchOsFontsSubpageTitleNormalFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsFontsSubpageTitleStrongFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsFontsSubpageTitleStrongFontSize = aliasFontSizeFontSize18
    public static let switchOsFontsSubpageTitleStrongFontWeight = aliasFontWeightFontWeightMedium
    public static let switchOsFontsButtonNormalFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsFontsButtonNormalFontSize = aliasFontSizeFontSize15
    public static let switchOsFontsButtonNormalFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsFontsButtonActiveFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsFontsButtonActiveFontSize = aliasFontSizeFontSize15
    public static let switchOsFontsButtonActiveFontWeight = aliasFontWeightFontWeightSemibold
    public static let switchOsFontsMainNavigationNormalFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsFontsMainNavigationNormalFontSize = aliasFontSizeFontSize14
    public static let switchOsFontsMainNavigationNormalFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsFontsMainNavigationActiveFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsFontsMainNavigationActiveFontSize = aliasFontSizeFontSize14
    public static let switchOsFontsMainNavigationActiveFontWeight = aliasFontWeightFontWeightSemibold
    public static let switchOsFontsFormTextFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsFontsFormTextFontSize = aliasFontSizeFontSize14
    public static let switchOsFontsFormTextFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsFontsCardNameNormalFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsFontsCardNameNormalFontSize = aliasFontSizeFontSize16
    public static let switchOsFontsCardNameNormalFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsFontsCardNameStrongFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsFontsCardNameStrongFontSize = aliasFontSizeFontSize16
    public static let switchOsFontsCardNameStrongFontWeight = aliasFontWeightFontWeightMedium
    public static let switchOsFontsBodyTextFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsFontsBodyTextFontSize = aliasFontSizeFontSize15
    public static let switchOsFontsBodyTextFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsFontsSublineTextFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsFontsSublineTextFontSize = aliasFontSizeFontSize12
    public static let switchOsFontsSublineTextFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsFontsSectionTitleNormalFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsFontsSectionTitleNormalFontSize = aliasFontSizeFontSize14
    public static let switchOsFontsSectionTitleNormalFontWeight = aliasFontWeightFontWeightRegular
    public static let switchOsFontsSectionTitleStrongFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsFontsSectionTitleStrongFontSize = aliasFontSizeFontSize14
    public static let switchOsFontsSectionTitleStrongFontWeight = aliasFontWeightFontWeightBold
    public static let switchOsFontsLargeTitleStrongFontFamily = aliasFontFamilyFontFamilyAndroid
    public static let switchOsFontsLargeTitleStrongFontSize = aliasFontSizeFontSize30
    public static let switchOsFontsLargeTitleStrongFontWeight = aliasFontWeightFontWeightBold
}